export class CreatePropertyPage{
    CreatePropertyPage(){

    }
    setLocationName(locationName){
        cy.get('.ucPS_EditControl.ucPS_TextBox').eq(0).type(locationName)
    }
    setLocationCode(locationCode){
        cy.get('.ucPS_EditControl.ucPS_TextBox').eq(1).type(locationCode)
    }
    setPropertyAddress1(propAddrs1){
        cy.get('.ucPS_EditControl.ucPS_TextBox').eq(2).type(propAddrs1)
    }
    setPropertyAddress2(propAddrs2){
        cy.get('.ucPS_EditControl.ucPS_TextBox').eq(3).type(propAddrs2)
    }
    selectCountry(country){
        cy.get('.ucPS_EditControl.standardDropdown').eq(0).select(country)
    }
    setCounty(county){
        cy.get('.ucPS_EditControl.ucPS_TextBox').eq(5).type(county)
    }
    selectState(state){
        cy.get('.ucPS_EditControl.standardDropdown').eq(1).select(state)
    }
    setPostal(postal){
        cy.get('.ucPS_EditControl.ucPS_TextBox').eq(4).type(postal)
    }
    setCity(city){
        cy.get('.ucPS_EditControl.ucPS_TextBox').eq(6).type(city)
    }
    selectCodeType(codeType){
        cy.get('.ucPS_EditControl.standardDropdown').eq(2).select(codeType)
    }
    selectStatus(status){
        cy.get('.ucPS_EditControl.standardDropdown').eq(3).type('{downArrow}')
    }
    selectCurrecy(currency){
        cy.get('.ucPS_EditControl.standardDropdown').eq(4).select(currency)
    }
    selectChartType(chartType){
        cy.get('.ucPS_EditControl.standardDropdown').eq(5).select(chartType)
    }
    selectLocationType(locationType){
        cy.get('.ucPS_EditControl.standardDropdown').eq(6).select(locationType)
    }
    setSqFtRentable(sqft){
        cy.get('.ucPS_EditControl.ucPS_TextBox').eq(7).type(sqft)
    }
    setSqFtUsable(sqft){
        cy.get('.ucPS_EditControl.ucPS_TextBox').eq(8).type(sqft)
    }
    setNoBuildings(buildings){
        cy.get('.ucPS_EditControl.ucPS_TextBox').eq(9).type(buildings)
    }
    setNoFloors(floors){
        cy.get('.ucPS_EditControl.ucPS_TextBox').eq(10).type(floors)
    }
    selectBuildingList(buildingList){
        cy.get('.ucPS_EditControl.standardDropdown').eq(7).select(buildingList)
    }
    selectRegion(region){
        cy.get('.ucPS_EditControl.standardDropdown').eq(9).select(region)
    }
    selectAssetType(assetType){
        cy.get('.ucPS_EditControl.standardDropdown').eq(11).select(assetType)
    }
    selectCurrencyConversion(currencyConversion){
        cy.get('.ucPS_EditControl.standardDropdown').eq(4).select(currencyConversion)
    }
    selectPropGroup5(propGroup){
        cy.get('.ucPS_EditControl.standardDropdown').eq(5).select(propGroup)
    }
    selectPropGroup6(propGroup){
        cy.get('.ucPS_EditControl.standardDropdown').eq(7).select(propGroup)
    }
    selectPropGroup7(propGroup){
        cy.get('.ucPS_EditControl.standardDropdown').eq(9).select(propGroup)
    }
    selectPropGroup8(propGroup){
        cy.get('.ucPS_EditControl.standardDropdown').eq(14).select(propGroup)
    }
    checkManageSpace(){
        cy.get('.ucPS_cbAutoManage').click()
    }
    clickSave(){
        cy.get('[type="submit"]').eq(4).click()
    }


    
}